### ISSUE TITLE
.txt input error NVivo

### ISSUE THREAD

**Issue by RKHWU** [SecurityEssentials/Teams2NVivo#10]
I seem to be having problems with the online converter - using a .vtt file downloaded from the Teams chat, when I import the converted .txt file into NVivo 12 and use the options "One transcript row for each tab-delimited line, File includes header row," I get an error in the Data Preview of  "Line 2 : Each line must contain the same number of tab characters."

I've tried with different .vtt files and get the same error, also checked the files themselves and tried to adjust Line two but no success.  I can't anonymise the files to attach unfortunately due to the transcript content but hoping you can help!

**Comment by charlesweir** [comment]
Please would you edit your files manually to provide something anonymous to test with. So long as I have something that has the same behaviour I can work on it.

**Comment by charlesweir** [comment]
This seems to be due to the change in Teams format that we have detected separately. Now fixed.
