### ISSUE TITLE
Correction for teams transcripts

### ISSUE THREAD

**Issue by lancsSteve** [SecurityEssentials/Teams2NVivo#6]
This script is proving a VERY effective way of working around the new way that Microsoft have hobbled transcription and recording in teams once stream is disabled and it all goes via OneDrive.

So the new way that Teams creates transcripts is that if you make multiple recordings (each starting at 00:00:00) from a meeting but one single transcript for the whole meeting. So... You often end up with transcripts that don't fit as they have a meeting timestamp NOT a rcecroding time stamp.

This is a pain - but you can work it out if you listen to recording, identify timestamp for first line and then work out how many hh:mm:ss to subtract, then translate that into seconds.

It would be really nice to have a better tool that would help.

IDEAS:
change to hh:mm:ss to add or remove not just seconds.

OR

Include a "transcript starts at hh:mm:ss box and it does that maths for you...

I can share example VTT files and a recording to illustrate.

**Comment by charlesweir** [comment]
Implemented.
