### ISSUE TITLE
ATLAS.ti / MAXQDA friendly options

### ISSUE THREAD

**Issue by lancsSteve** [SecurityEssentials/Teams2NVivo#7]
Given other issue flagged here (teams transcritps) there's a real use for this script for the time-shift but NOT for NVivo.

So if there were an option fo a script that had fewer NVivo adaptations that's be awesome i.e.

1 - stripping out VTT formatting
2 - time-shifting timestamps with "transcript starts at hh:mm:ss" so it reformats that time stamp to 00:00:00 and co-ordinates with new video
3 - Option (yes/no) to concatenate lines with same speaker - useful for NVivo less so for other programmes.
4 - option (yes/no) include header row for timestamp / speaker / content

**Comment by charlesweir** [comment]
Don't have use cases for these. NGTF.
