### ISSUE TITLE
Check for duplicate times

### ISSUE THREAD

**Issue by lancsSteve** [SecurityEssentials/Teams2NVivo#8]
Rare - and mostly resolved whit the natty option to concatenate same speaker times together but NVivo throws a RIGHT hissy fit if there are two or more lines with the same time stamp. And like most hissy fits it's pretty incomprehensible so you have to work out which line caused the error.

Would be good to have a quick check in the script for any duplicate entries and/or an option to say "auto-adjust duplicate time stamps by +1s".

**Comment by charlesweir** [comment]
Functionality is already present for pairs of duplicate entries. I've not seen a trio - need example code before fixing.
