### ISSUE TITLE
Missing speaker

### ISSUE THREAD

**Issue by lancsSteve** [SecurityEssentials/Teams2NVivo#9]
Code comment says:
Put in as blank, and rely on NVivo 'fill down' or the concatenation below.

This doesn't always seem to work - have had NVivo throw an exception about number of tabs being wrong. If possible replace with 

(?) 

To try and follo trsnacription conventions for CA and others - see https://www.oscar-romeo.com/docs/Transcriptions_Conventions.pdf

**Comment by charlesweir** [comment]
No example code. Cannot fix.

**Comment by charlesweir** [comment]
@lancsSteve Please provide an example VTT file showing the problem.

**Comment by lancsSteve** [comment]
Will be doing some testing with various scripts coming up and will make sure I do q better job documenting and keeping a problem script and steps to share :-)

**Comment by charlesweir** [comment]
Closed for now.
